services:
  statistic-server:
    build: ewm-statistic/ewm-statitstic-service
    image: ewm-statitstic-service
    container_name: ewm-statitstic-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistic-db
      - SPRING_DATASOURCE_USERNAME=dbstats
      - SPRING_DATASOURCE_PASSWORD=12345

  statistic-db:
    image: postgres:16.1
    container_name: statistic-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=statistic-db
      - POSTGRES_USER=dbstats
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build:  ewm-main
    image:  ewm-service
    container_name:  ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=dbewm
      - SPRING_DATASOURCE_PASSWORD=12345
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=dbewm
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./volumes/postgres/ewm_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10