services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=statistic
      - POSTGRES_USER=userstats
      - POSTGRES_PASSWORD=12345
    networks:
      - explore-network

  stats-server:
    build: ./ewm-statistic/ewm-statistic-service
    container_name: ewm-statistic-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistic
      - SPRING_DATASOURCE_USERNAME=userstats
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      - explore-network

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "4265:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=userewm
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./volumes/postgres/ewm_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - explore-network

  ewm-service:
    build:  ./ewm-main
    container_name:  ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=userewm
      - SPRING_DATASOURCE_PASSWORD=12345
      - STATS_SERVER_URL=http://stats-server:9090
    networks:
      - explore-network

networks:
  explore-network:
    driver: bridge